version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.apache.commons:commons-compress
    versions:
    - "1.19"
  - dependency-name: com.mycila:license-maven-plugin
    versions:
    - "3.0"
    - "4.0"
  - dependency-name: com.fasterxml.jackson.module:jackson-module-jaxb-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.datatype:jackson-datatype-joda
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.dataformat:jackson-dataformat-xml
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.scala-lang:scala-library
    versions:
    - 2.13.4
  - dependency-name: org.apache.logging.log4j:log4j-1.2-api
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-slf4j-impl
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-core
    versions:
    - 2.14.0
  - dependency-name: org.apache.logging.log4j:log4j-api
    versions:
    - 2.14.0
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.27"
  - dependency-name: org.glassfish.jersey.media:jersey-media-json-jackson
    versions:
    - 2.29.1
  - dependency-name: org.glassfish.jersey.media:jersey-media-multipart
    versions:
    - 2.29.1
  - dependency-name: org.glassfish.jersey.inject:jersey-hk2
    versions:
    - 2.29.1
  - dependency-name: org.glassfish.jersey.core:jersey-common
    versions:
    - 2.29.1
  - dependency-name: org.glassfish.jersey.core:jersey-server
    versions:
    - 2.29.1
  - dependency-name: org.glassfish.jersey.containers:jersey-container-grizzly2-http
    versions:
    - 2.29.1
